export const Donors = [
    {
      id: 1,
      name: "Majeed Ali",
      age: 25,
      bloodGroup: "O-",
      city: "Lahore",
      contact: "0321-1234567",
      Date: '09/10/2024'
    },
    {
      id: 2,
      name: "Hunain Ali",
      age: 22,
      bloodGroup: "AB+",
      city: "Islamabad",
      contact: "0317-0062609",
       Date: '03/10/2024'
    },
    {
      id: 3,
      name: "Junaid Khan",
      age: 25,
      bloodGroup: "AB-",
      city: "RYK",
      contact: "0321-1234567",
       Date: '14/10/2024'
    },
    {
      id: 4,
      name: "Esha Saeed",
      age: 25,
      bloodGroup: "A+",
      city: "Lahore",
      contact: "0321-1234567",
       Date: '26/10/2024'
    },
    {
      id: 5,
      name: "Jaffar Shah",
      age: 24,
      bloodGroup: "AB+",
      city: "Ghotki",
      contact: "0321-1234567",
       Date: '08/08/2024'
    },
    {
      id: 6,
      name: "Hasnain Haider",
      age: 24,
      bloodGroup: "O-",
      city: "Layyah",
      contact: "0321-1234567",
       Date: '09/01/2024'
    },

  ];


 export const items = [
    { label: 'Abbottabad', value: 'Abbottabad' },
    { label: 'Layyah', value: 'Layyah' },
    { label: 'Bahawalnagar', value: 'Bahawalnagar' },
    { label: 'Bahawalpur', value: 'Bahawalpur' },
    { label: 'Burewala', value: 'Burewala' },
    { label: 'Chakwal', value: 'Chakwal' },
    { label: 'Chiniot', value: 'Chiniot' },
    { label: 'Dadu', value: 'Dadu' },
    { label: 'Daska', value: 'Daska' },
    { label: 'Dera Ghazi Khan', value: 'Dera Ghazi Khan' },
    { label: 'Faisalabad', value: 'Faisalabad' },
    { label: 'Gujranwala', value: 'Gujranwala' },
    { label: 'Gujrat', value: 'Gujrat' },
    { label: 'Hafizabad', value: 'Hafizabad' },
    { label: 'Hyderabad', value: 'Hyderabad' },
    { label: 'Islamabad', value: 'Islamabad' },
    { label: 'Jacobabad', value: 'Jacobabad' },
    { label: 'Jhang', value: 'Jhang' },
    { label: 'Karachi', value: 'Karachi' },
    { label: 'Kasur', value: 'Kasur' },
    { label: 'Khairpur', value: 'Khairpur' },
    { label: 'Khanewal', value: 'Khanewal' },
    { label: 'Khanpur', value: 'Khanpur' },
    { label: 'Khuzdar', value: 'Khuzdar' },
    { label: 'Kohat', value: 'Kohat' },
    { label: 'Lahore', value: 'Lahore' },
    { label: 'Larkana', value: 'Larkana' },
    { label: 'Mandi Bahauddin', value: 'Mandi Bahauddin' },
    { label: 'Mansehra', value: 'Mansehra' },
    { label: 'Mardan', value: 'Mardan' },
    { label: 'Mirpur Khas', value: 'Mirpur Khas' },
    { label: 'Multan', value: 'Multan' },
    { label: 'Muridke', value: 'Muridke' },
    { label: 'Muzaffargarh', value: 'Muzaffargarh' },
    { label: 'Nawabshah', value: 'Nawabshah' },
    { label: 'Nowshera', value: 'Nowshera' },
    { label: 'Okara', value: 'Okara' },
    { label: 'Pakpattan', value: 'Pakpattan' },
    { label: 'Peshawar', value: 'Peshawar' },
    { label: 'Quetta', value: 'Quetta' },
    { label: 'Rahim Yar Khan', value: 'Rahim Yar Khan' },
    { label: 'Rawalpindi', value: 'Rawalpindi' },
    { label: 'Sadiqabad', value: 'Sadiqabad' },
    { label: 'Sahiwal', value: 'Sahiwal' },
    { label: 'Sargodha', value: 'Sargodha' },
    { label: 'Sheikhupura', value: 'Sheikhupura' },
    { label: 'Shikarpur', value: 'Shikarpur' },
    { label: 'Sialkot', value: 'Sialkot' },
    { label: 'Sukkur', value: 'Sukkur' },
    { label: 'Swabi', value: 'Swabi' },
    { label: 'Tando Adam', value: 'Tando Adam' },
    { label: 'Tando Allahyar', value: 'Tando Allahyar' },
    { label: 'Turbat', value: 'Turbat' },
    { label: 'Vehari', value: 'Vehari' },
    { label: 'Wah Cantonment', value: 'Wah Cantonment' },
    { label: 'Wazirabad', value: 'Wazirabad' },
    { label: 'Zhob', value: 'Zhob' }
];